### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by onthetunnel** [imizaac/BinanceArbitrage#2]
hello , can you add how to install , setting and use for it please , Thanks!

**Comment by Bobert-Brockson** [comment]
Hey @onthetunnel 

In its current state it is not capable of being used as a production level tool. There were serious concerns that needed to be answered before moving forward with the project. These included overarching server architecture, the computation time, child processes, and finding servers with minimal latency to the Binance servers. 

In my research I found that it is quite likely that other people are performing this style of trading simultaneously which would mean that you would have to compete with them to trade faster. This leads me to believe that javascript is not the ideal language to do this, and that this software should be ported into C++ or a similar lower level language.

As a result I have not created build tools for this project, nor have I bundled it into a pretty software package for ease of configuration, but you can still use it. 

Note: It is currently suffering from an unfixed security vulnerability.

1. git clone the package onto your system, 
2. go into that directory and run NPM install, 
3. add your API keys to the Websockets.js file.
4. run the main.js file with node

You should be up and running. But I'm gonna stress here. This currently doesn't do any trading and probably shouldn't until you update the security vulnerabilities. You would have to create a trading algorithm to act on the information this algorithm finds.

**Comment by onthetunnel** [comment]
Many Thanks For you answer but for me is hard to understand ...srry about that ...
i run it and it just count down 1 to 19 ...and doesnt open any trade ... hope you or other Master can fix it .. Thanks You!

**Comment by Bobert-Brockson** [comment]
Yes, It does not trade. This has not been implemented because it would not be fast enough to get the trades profitably in this language. If you are interested in actually trading, use this as a model to write this in C++

**Comment by onthetunnel** [comment]
i found some triangular arbitrage project on github , but i dont know how to use it , can you see it ? Thanks!
https://github.com/kemargrant/c4d (JS)
https://github.com/MikeAnthonyG/BinBot (PYTHON)
https://github.com/wilsontheory/binance_arbitrage (JAVA)

**Comment by Bobert-Brockson** [comment]
I would recommend seeking out the Java implementation as it would likely have the best performance.

**Comment by onthetunnel** [comment]
ok , Thanks You !! hope you can be a amazing work on crypto ! God bless you Thanks You!
